### ISSUE TITLE
Where is this API key ? 

### ISSUE THREAD

**Issue by SwissWeb** [sputinyk/laravel-4-bing-translation#1]
Hello,
I can't get this to work, probably because I'm not sure what secret or API key...  Tried putting App Id or secret or azure translate API key... None work. Any ideas ?

**Comment by tanigami** [comment]
I don't see what to put there either… @sputinyk ?

**Comment by tanigami** [comment]
OK now I see the API key is actually what's called AppID, which is deprecated.
https://msdn.microsoft.com/en-us/library/hh454950.aspx
Need changes.

**Comment by netojose** [comment]
@SwissWeb  and @tanigami 

Guys first of all, sorry for my bad english, and for a long time for response.
the file with the api key is generated via artisan command:

**php artisan config:publish sputinyk/bing-translation**

A file is generated in:

_app/config/packages/sputinyk/bingtranslation/config.php_

I tested today and still works :dancer:
